name: Called Workflow test json
on:
  workflow_call:
    inputs:
      my_input:
        required: true
        type: string
    outputs:
      my_output:
        description: "An output value"
        value: ${{ jobs.example_job.outputs.my_output_result }}


jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      my_output_result: ${{ steps.set-output.outputs.value }}
    steps:
      - name: Set output
        id: set-output
        run: echo "value=Hello ${{ inputs.my_input }}" 